import turtle


tr = turtle.getturtle()
len = 20
while True:
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)

    tr.left(180)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    tr.right(120)
    tr.forward(len)
    tr.left(60)
    tr.forward(len)
    
turtle.mainloop()